domain: janene-smith.github.io
url: https://janene-smith.github.io

title: Welcome to Janene Smith's homepage!
description: Feel free to bookmark this to keep an eye on my project updates.
theme: cayman
